// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoMessage_EchoMessage_FullMethodName = "/message.EchoMessage/echoMessage"
)

// EchoMessageClient is the client API for EchoMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoMessageClient interface {
	EchoMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type echoMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoMessageClient(cc grpc.ClientConnInterface) EchoMessageClient {
	return &echoMessageClient{cc}
}

func (c *echoMessageClient) EchoMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, EchoMessage_EchoMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoMessageServer is the server API for EchoMessage service.
// All implementations must embed UnimplementedEchoMessageServer
// for forward compatibility.
type EchoMessageServer interface {
	EchoMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedEchoMessageServer()
}

// UnimplementedEchoMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoMessageServer struct{}

func (UnimplementedEchoMessageServer) EchoMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoMessage not implemented")
}
func (UnimplementedEchoMessageServer) mustEmbedUnimplementedEchoMessageServer() {}
func (UnimplementedEchoMessageServer) testEmbeddedByValue()                     {}

// UnsafeEchoMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoMessageServer will
// result in compilation errors.
type UnsafeEchoMessageServer interface {
	mustEmbedUnimplementedEchoMessageServer()
}

func RegisterEchoMessageServer(s grpc.ServiceRegistrar, srv EchoMessageServer) {
	// If the following call pancis, it indicates UnimplementedEchoMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoMessage_ServiceDesc, srv)
}

func _EchoMessage_EchoMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoMessageServer).EchoMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoMessage_EchoMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoMessageServer).EchoMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoMessage_ServiceDesc is the grpc.ServiceDesc for EchoMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.EchoMessage",
	HandlerType: (*EchoMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "echoMessage",
			Handler:    _EchoMessage_EchoMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
