# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\" \n\x0fMessageResponse\x12\r\n\x05title\x18\x01 \x01(\t\"0\n\x0eMessageRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2Q\n\x0b\x45\x63hoMessage\x12\x42\n\x0b\x65\x63hoMessage\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponse\"\x00\x42\x0bZ\t./messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./message'
  _globals['_MESSAGERESPONSE']._serialized_start=26
  _globals['_MESSAGERESPONSE']._serialized_end=58
  _globals['_MESSAGEREQUEST']._serialized_start=60
  _globals['_MESSAGEREQUEST']._serialized_end=108
  _globals['_ECHOMESSAGE']._serialized_start=110
  _globals['_ECHOMESSAGE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
